name: nexml_slomo
channels:
    - defaults
    - conda-forge
    - pytorch
dependencies:
    - python=3.7
    - pytorch=1.5
    - xarray
    - numpy
    - scipy
    - pip
    - pandas
    - torchvision
    - opencv
    - jupyterlab
    - seaborn
    - tensorboard
    - pyhdf
    - joblib
    - pip:
        - petastorm
